import { Antonio } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import BottomNav from "@/components/BottomNav";
import LoadedImage from "@/components/common/LoadedImage";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const bebas = Antonio({
  subsets: ["latin"],
  variable: "--font-bebas",
  weight: ["200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} font-bebas  bg-accent_blue`}>
        <Navbar />
        <div className="w-full h-screen fixed top-0 left-0 z-[-1]">
          <LoadedImage
            alt="bg"
            src={"/images/background.png"}
            fill={true}
            objectFit="cover"
            priority={true}
          />
        </div>

        {children}
        <BottomNav />
      </body>
    </html>
  );
}
