import { Antonio } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import BottomNav from "@/components/BottomNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const bebas = Antonio({
  subsets: ["latin"],
  variable: "--font-bebas",
  weight: ["200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} font-bebas`}>
        <Navbar />
        <div className="w-full h-screen fixed top-0 left-0 z-[-1]">
          <Image
            alt="bg"
            src={"/images/background.png"}
            fill
            objectFit="cover"
            priority
          />
        </div>

        {children}
        <BottomNav />
      </body>
    </html>
  );
}
